"""The Docker Hub applications the data modules run, and how they're configured.

Kept in one place so modules that run the same application (PostgREST in
modules 10 and 11, the database client tasks) stay identical. Every image
is pinned to a tag that existed on Docker Hub when this was written -
re-check before changing them.

References:
- PostgREST configuration and tutorial 0:
  https://docs.postgrest.org/en/stable/references/configuration.html
  https://docs.postgrest.org/en/stable/tutorials/tut0.html
- https://hub.docker.com/r/postgrest/postgrest  https://hub.docker.com/_/postgres
- https://hub.docker.com/_/wordpress  https://hub.docker.com/_/mysql
"""

from __future__ import annotations

POSTGREST_IMAGE = "postgrest/postgrest:v16.4"
POSTGRES_CLIENT_IMAGE = "postgres:17-alpine"
WORDPRESS_IMAGE = "wordpress:6.9-apache"
MYSQL_CLIENT_IMAGE = "mysql:8.4"

# PostgREST: API traffic and the admin server (/live, /ready).
API_PORT = 3000
ADMIN_PORT = 3001

# The migration the PostgreSQL client task runs (psql reads it from stdin,
# so the :'app_password' variable is substituted - psql -c doesn't do that).
# Schema, table and roles follow PostgREST's tutorial 0; web_anon may also
# INSERT here so the API can write without authentication (learning only).
MIGRATION_SQL = """\
CREATE SCHEMA IF NOT EXISTS api;
CREATE TABLE IF NOT EXISTS api.todos (
  id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  done boolean NOT NULL DEFAULT false,
  task text NOT NULL,
  due  timestamptz
);
DO $$ BEGIN CREATE ROLE web_anon NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT, INSERT ON api.todos TO web_anon;
DO $$ BEGIN CREATE ROLE authenticator NOINHERIT LOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER ROLE authenticator WITH LOGIN PASSWORD :'app_password';
GRANT web_anon TO authenticator;
NOTIFY pgrst, 'reload schema';
"""

# The PostgreSQL client task: the migration by default, or any SQL in $SQL.
CLIENT_COMMAND = (
    'if [ -n "$SQL" ]; then psql -v ON_ERROR_STOP=1 -c "$SQL"; '
    'else printf "%s" "$MIGRATION" | psql -v ON_ERROR_STOP=1 -v app_password="$APP_PASSWORD"; fi'
)

# The MySQL client task: runs $SQL against $DB_NAME.
MYSQL_CLIENT_COMMAND = 'mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "$SQL"'
MYSQL_DEFAULT_SQL = (
    "CREATE TABLE IF NOT EXISTS visits (id INT AUTO_INCREMENT PRIMARY KEY, "
    "source VARCHAR(64), at TIMESTAMP DEFAULT CURRENT_TIMESTAMP); "
    "INSERT INTO visits (source) VALUES ('ecs-one-off-task'); "
    "SELECT COUNT(*) AS visits, MAX(at) AS last_visit FROM visits;"
)

# --- nginx with structured access logs (modules 19 and 21) --------------------
NGINX_IMAGE = "nginx:1.30-alpine"
LOAD_IMAGE = "curlimages/curl:8.22.0"

# nginx writes one JSON object per request to stdout (the official image links
# /var/log/nginx/access.log to stdout), so log tools can filter on fields.
NGINX_CONF = r"""log_format json_log escape=json '{"time":"$time_iso8601","method":"$request_method","path":"$uri","status":$status,"bytes":$body_bytes_sent,"request_time":$request_time,"remote_addr":"$remote_addr","user_agent":"$http_user_agent"}';
server {
  listen 80;
  access_log /var/log/nginx/access.log json_log;
  location = /health { access_log off; return 200 "ok\n"; }
  location = /error  { return 500 "simulated error\n"; }
  location /         { return 200 "hello from $hostname\n"; }
}
"""
# The configuration arrives in $NGINX_CONF and is written before nginx starts.
NGINX_START = "printf '%s' \"$NGINX_CONF\" > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

# WORKERS loops of curl against $URL for DURATION seconds; every ERROR_EVERY-th request hits /error.
LOAD_COMMAND = (
    'end=$(( $(date +%s) + DURATION )); echo "load: $WORKERS workers, 1 error every $ERROR_EVERY requests"; '
    'for i in $(seq 1 "$WORKERS"); do ( n=0; while [ "$(date +%s)" -lt "$end" ]; do n=$((n+1)); '
    'if [ $((n % ERROR_EVERY)) -eq 0 ]; then p=error; else p=; fi; curl -s -o /dev/null "$URL$p"; done; '
    'echo "worker $i: $n requests" ) & done; wait; echo "load: done"'
)
