"""Database credentials and network access, built the same way in every data module.

The master password is generated by Secrets Manager and never appears in
code or in the synthesized template. The secret is created with a fixed
name and passed to the database as the dynamic reference
`{{resolve:secretsmanager:<name>:SecretString:password::}}` - by *name*,
not through `rds.Credentials.from_generated_secret()`, because that shortcut
builds the reference with `Fn::Join` + `Ref`, which floci rejects
("Invalid Secrets Manager dynamic reference") - see REQUIREMENTS.md
section 10. It works identically on real AWS.

ECS tasks receive the password the normal ECS way: `ecs.Secret.from_secrets_manager(secret, "password")`,
resolved by the task execution role when the task starts.

References:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-secretsmanager.html
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html
"""

from __future__ import annotations

from aws_cdk import RemovalPolicy, SecretValue
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from shared.config import AppConfig
from shared.naming import resource_name
from shared.tagging import apply_name_tag

# The characters the CDK's own generated RDS secrets exclude - unsafe in
# connection strings and shells.
EXCLUDED_CHARACTERS = " %+~`#$&*()|[]{}:;<>?!'/@\"\\"


def generated_credentials(
    scope: Construct, config: AppConfig, purpose: str, username: str, construct_id: str = "MasterSecret"
) -> tuple[secretsmanager.Secret, str]:
    """A `{"username": ..., "password": <generated>}` secret, and its fixed name."""
    secret_name = resource_name(config.product, config.environment, "secret", purpose)
    secret = secretsmanager.Secret(
        scope,
        construct_id,
        secret_name=secret_name,
        description=f"{purpose}: generated database credentials (never in code)",
        generate_secret_string=secretsmanager.SecretStringGenerator(
            secret_string_template=f'{{"username": "{username}"}}',
            generate_string_key="password",
            exclude_characters=EXCLUDED_CHARACTERS,
        ),
        removal_policy=RemovalPolicy.DESTROY,
    )
    apply_name_tag(secret, secret_name)
    return secret, secret_name


def password_reference(secret_name: str) -> SecretValue:
    """The by-name dynamic reference to the secret's `password` field."""
    return SecretValue.secrets_manager(secret_name, json_field="password")
